# .goreleaser.yml
builds:
  - binary: terraform-provider-exasol
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
